### PR TITLE
Admin/Owner: substitute $version in quit and part messages (also make part messages configurable)

### LINKED ISSUE #391: There isn't a way to set default part message with a configuration variable.
The only configuration variable to set about default messages is for quitting, supybot.plugins.Owner.quitMsg

### PR DESCRIPTION
**Pull request by GLolol**
Closes #391.

This also makes the default part message the Supybot version instead of the nick's caller. Quit messages are optional anyways for IRC, so just having someone's nick inside a part message isn't very intuitive or meaningful. When `config plugins.admin.partmsg` is blank, simply no part message will be used.

edit: This also merges the changes in #1043 and supports other substitutions too (`$nick`, etc.).

### CODE REVIEW

**Comment by ProgVal** [comment]
Could you use template strings instead? https://docs.python.org/3/library/string.html#template-strings

**Comment by ProgVal** [comment]
Actually, this may be even better: https://github.com/ProgVal/Limnoria/blob/master/src/ircutils.py#L668

**Comment by GLolol** [comment]
Would it be appropriate to add another item in the vars dict for this? (`version: 'Supybot %s' % conf.version`)

I'll take a look at it later today.

**Comment by ProgVal** [comment]
absolutely

**Comment by ProgVal** [comment]
`ircmsgs.ping`?

**Comment by GLolol** [comment]
The `ircutils.standardSubstitute` function expects a msg object (e.g. it expands `$nick` to `msg.nick`), but Ctrl-C at console isn't an IRC event and thus doesn't have one.

**Comment by ProgVal** [comment]
I think it would be better to have an altered version of standardSubstitute that can be used without a msg object

**Comment by GLolol** [comment]
Where should such a function be placed?

**Comment by ProgVal** [comment]
Actually, I made a change to `standardSubstitute` so it now accepts `None` as `irc` and `msg`: https://github.com/ProgVal/Limnoria/commit/cb6669015e4dfd113f3daf6e3797708d7ce307c1

Could you update your patch to handle that?

**Comment by GLolol** [comment]
Done.

**Comment by Mikaela** [comment]
What is the current status of this pull request?

**Pull request merged**
