### PR TITLE
add usesendMsg=False to irc.reply() to use sendMsg() instead of queueMsg...

### PR DESCRIPTION
**Pull request by ddan39**
for plugin coding if you want to explicitly tell irc.reply() to use sendMsg instead of the default queueMsg

### CODE REVIEW

**Comment by ProgVal** [comment]
https://github.com/ProgVal/Limnoria/pull/1007#issuecomment-70358272

**Comment by ddan39** [comment]
changed most of that :)

i think usesendMsg is good arg now.. yea?

i agree about the sendMsg variable name, but dont know what better to use, and imo it doesnt matter much since it is local to that function

**Comment by ProgVal** [comment]
> i think usesendMsg is good arg now.. yea?
Nope, same issue. You should use something like `queueMsg` or `sendImmediately`, which tells what the argument actually does, instead of referring to an internal name of the core

**Comment by ddan39** [comment]
yes was thinking something just like that, sendNow or fast... but sendImmediately is even nicer, and actually what the doc string for sendMsg says it does :)

**Comment by ddan39** [comment]
changed the arg name, but left sendMsg variable...  nothing really looked better. only idea was msgSender, but it just doesnt look nice :(

last idea is to do "sendMsg(msg) if sendImmediately else queueMsg(msg)"  at every spot that it does the sendMsg()...

**Pull request merged**
