### PR TITLE
Update TL;DR install instructions with missing dependency

### PR DESCRIPTION
**Pull request by voltagex**
Added python3-wheel dependency, otherwise I got an error running bdist_wheel

### CODE REVIEW

**Comment by jlu5** [comment]
At a cursory glance, [python3-pip](https://packages.debian.org/sid/python3-pip) [recommends](https://unix.stackexchange.com/questions/77053/apt-installing-more-packages-than-specified-as-dependencies/77076#77076) python3-wheel, meaning that it should be pulled in automatically if your system is configured to install recommends (this is the default on Debian and Ubuntu). But I suppose being explicit here doesn't hurt. :+1:

**Comment by ProgVal** [comment]
I don't understand. You have this issue when *installing* Limnoria?

**Comment by voltagex** [comment]
@ProgVal 

```
voltagex@vps194396:~$ sudo apt-get install python3 python3-pip                                                                                                                                                                                                 [514/514]
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3 is already the newest version (3.5.3-1).
python3 set to manually installed.
The following packages were automatically installed and are no longer required:
  linux-image-4.9.0-4-amd64 linux-image-4.9.0-6-amd64
Use 'sudo apt autoremove' to remove them.
Recommended packages:
  build-essential python3-wheel
The following NEW packages will be installed:
  python-pip-whl python3-pip
0 upgraded, 2 newly installed, 0 to remove and 25 not upgraded.
Need to get 1,542 kB of archives.
After this operation, 2,223 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 python-pip-whl all 9.0.1-2+deb9u1 [1,399 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 python3-pip all 9.0.1-2+deb9u1 [142 kB]
Fetched 1,542 kB in 0s (11.3 MB/s)
Selecting previously unselected package python-pip-whl.
(Reading database ... 44410 files and directories currently installed.)
Preparing to unpack .../python-pip-whl_9.0.1-2+deb9u1_all.deb ...
Unpacking python-pip-whl (9.0.1-2+deb9u1) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../python3-pip_9.0.1-2+deb9u1_all.deb ...
Unpacking python3-pip (9.0.1-2+deb9u1) ...
Setting up python-pip-whl (9.0.1-2+deb9u1) ...
Setting up python3-pip (9.0.1-2+deb9u1) ...
Processing triggers for man-db (2.7.6.1-2) ...
voltagex@vps194396:~$ pip3 install --user limnoria
Collecting limnoria
  Downloading https://files.pythonhosted.org/packages/d5/5b/8c161c96732a08517347a5db8a983df8a59d4eda1df2e00aad9e3e2e8a7c/limnoria-2019.12.15.tar.gz (900kB)
    100% |████████████████████████████████| 901kB 1.0MB/s
Building wheels for collected packages: limnoria
  Running setup.py bdist_wheel for limnoria ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bzl57me5/limnoria/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))"
 bdist_wheel -d /tmp/tmpc1q7bmp8pip-wheel- --python-tagcp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for limnoria
  Running setup.py clean for limnoria
Failed to build limnoria
Installing collected packages: limnoria
  Running setup.py install for limnoria ... done
Successfully installed limnoria-2019.12.15
voltagex@vps194396:~$ supybot-wizard
-bash: supybot-wizard: command not found

```

**Comment by voltagex** [comment]
Ah yeah, I see what you mean. I'm not sure if this box was reconfigured from default - it's a Debian image from Aliyun ECS.

**Comment by ProgVal** [comment]
It looks like the install succeeds anyway, though. Can you check that `~/.local/bin/supybot-wizard` doesn't exist?

**Comment by voltagex** [comment]
Not easily as I fixed my install by installing python3-wheel and modifying my PATH.

**Pull request merged**
