### PR TITLE
Revert "Improve order of connect messages." (SASL fix on freenode)

### PR DESCRIPTION
**Pull request by GLolol**
This reverts commit a2004b7150bde2c6c89d088e7e16fd7dcea38b50.

I want to revert this change because it caused SASL to fail for me on at least Freenode. The issue stems, I believe, from `CAP` being requested *after* initial signon: A fast responding server would have connected the bot as a regular user before it gets a chance to identify via SASL. Instead, it simply throws this error, basically stating that connected users can't use SASL.

`ERROR 2015-05-21T17:39:13 Unhandled error message from server: IrcMsg(prefix="holmes.freenode.net", command="462", args=('firehazard', 'You may not reregister'))`

### CODE REVIEW

**Comment by ProgVal** [comment]
Can you fix the tests to make them pass?

**Comment by GLolol** [comment]
Oh, I just noticed that they broke. Will do later today.

**Comment by ProgVal** [comment]
poke

**Comment by GLolol** [comment]
I don't understand why it's failing... What else changed that has to be reverted?

**Comment by ProgVal** [comment]
The order of CAP REQ and PASS in the tests. https://travis-ci.org/ProgVal/Limnoria/jobs/63738435#L4419

Also, I can't merge your pull request, you have to merge testing into your branch.

**Comment by GLolol** [comment]
What... Why does this work on my local machine but not in Travis?

**Comment by ProgVal** [comment]
Have you thought of running setup.py install?

**Comment by GLolol** [comment]
The test results change by updating the files in `test/` regardless of whether `setup.py` is ran. I don't think `test/` is installed at all, only `supybot-test` changes.

**Comment by ProgVal** [comment]
Maybe you made a change in `src/` at some point

**Comment by GLolol** [comment]
I realize this didn't fix the issue properly, and SASL still broke randomly at times on freenode. It is superseded by #1122 and #1125.

**Pull request closed without merging**
