### PR TITLE
Allow to pass more arguments than just two to logging

### PR DESCRIPTION
**Pull request by wolfy1339**

### CODE REVIEW

**Comment by ProgVal** [comment]
What arguments are you talking about?

**Comment by ProgVal** [comment]
ping

**Comment by ProgVal** [comment]
ping?

**Comment by wolfy1339** [comment]
I am talking about self.log.debug and others. The formatting arguments

**Comment by ProgVal** [comment]
wasn't it already possible to pass more than two arguments?

**Comment by ProgVal** [comment]
ping?

**Pull request closed without merging**
