### PR TITLE
[discussion] Karma: refactor message parsing/limit Karma to nicks in channel

### PR DESCRIPTION
**Pull request by GLolol**
Limiting Karma to nicks only prevents things such as "I'm learning C++" from triggering a Karma response, which is a bit ridiculous.

### CODE REVIEW

**Comment by GLolol** [comment]
...Uhh actually I realize that really breaks the tests. Is it possible to create dummy users in the testcases to make this work properly?

**Comment by Mikaela** [comment]
> limit Karma to nicks in channel

I don't like this as many channels do `google++` etc meaning the service or something, not some nick in channel.

Also Karma defaults to not saying anything when Karma is increased/decreased.

**Comment by GLolol** [comment]
Maybe it makes more sense as a config variable, but I don't see the value of being able to assign karma to long strings of text. Maybe confining it to nicks or one word would be better.

**Comment by ProgVal** [comment]
There is `plugins.karma.allowUnaddressedKarma` for that.

**Pull request closed without merging**
