### PR TITLE
Karma: add an option to limit Karma to nicks 

### PR DESCRIPTION
**Pull request by GLolol**
This is essentially the better version of #1002, but making it a config option instead.

### CODE REVIEW

**Comment by ProgVal** [comment]
test cases, please :)

**Comment by GLolol** [comment]
Writing the tests is one thing, getting them to work is another. I don't know why it's not working.

```
FAIL: testOnlyNicks (Karma.test.KarmaTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/test.py", line 154, in runTest
    originalRunTest()
  File "./Karma/test.py", line 217, in testOnlyNicks
    self.assertNoResponse('abcd++')
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/test.py", line 314, in assertNoResponse
    self.failIf(m, 'Unexpected response: %r' % m)
AssertionError: IrcMsg(prefix="", command="PRIVMSG", args=('#test', 'Error: "abcd++" is not a valid command.')) is not false : Unexpected response: IrcMsg(prefix="", command="PRIVMSG", args=('#test', 'Error: "abcd++" is not a valid command.'))
```

```diff
diff --git a/plugins/Karma/test.py b/plugins/Karma/test.py
index f615646..0d855c3 100644
--- a/plugins/Karma/test.py
+++ b/plugins/Karma/test.py
@@ -204,4 +204,22 @@ class KarmaTestCase(ChannelPluginTestCase):
             karma.response.setValue(resp)
             karma.allowUnaddressedKarma.setValue(unaddressed)

+    def testOnlyNicks(self):
+        self.irc.nick = 'hello'
+        karma = conf.supybot.plugins.Karma
+        resp = karma.response()
+        onlynicks = karma.onlyNicks()
+        replynotcommand = conf.replyWhenNotCommand
+        try:
+            conf.replyWhenNotCommand = False
+            karma.onlynicks.setValue(True)
+            karma.response.setValue(True)
+            self.assertNoResponse('abcd++')
+            self.assertRegexp('hello--', 'is now')
+            self.assertNoResponse('abcd--')
+            self.assertRegexp('hello++', 'is now')
+        finally:
+            karma.onlynicks.setValue(onlynicks)
+            karma.response.setValue(resp)
+            conf.replyWhenNotCommand = replynotcommand
 # vim:set shiftwidth=4 softtabstop=4 expandtab textwidth=79:
```

**Comment by ProgVal** [comment]
`assertNoResponse` is for checking the bot does not respond to a command.
I think what you are looking for is `assertNoResponse` (example at the end of `Karma/test.py`)

**Comment by GLolol** [comment]
Tried that:

```
FAIL: testOnlyNicks (Karma.test.KarmaTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/test.py", line 154, in runTest
    originalRunTest()
  File "./Karma/test.py", line 217, in testOnlyNicks
    self.assertSnarfRegexp('hello--', 'is now')
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/test.py", line 343, in assertSnarfRegexp
    usePrefixChar=False, **kwargs)
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/test.py", line 336, in assertRegexp
    raise TimeoutError(query)
supybot.test.TimeoutError: 'hello--' timed out
```

**Comment by GLolol** [comment]
I have pushed the changes that I've made (they don't pass yet, but it's better than having to paste diffs here for every change).

**Comment by ProgVal** [comment]
That means the plugin does not answer to the message “hello--”.
* If it should answer -> fix the plugin
* If it should not answer -> use `assertSnarfNoResponse`

**Comment by GLolol** [comment]
The behavior works fine when I test it out on IRC, but not in the testcases. In this case I want to set `self.nick` to "hello", so that it is recognized as a nick in the channel. The bot should then reply for assigning Karma to "hello", but not anything that's not a nick (abcd).

I'm not sure if it's an incorrect usage of `self.nick` that's causing things to break, but I've used it before and it seems to work.

On IRC:

```
23:29 <@synnero> `config plugins.karma.onlynicks
23:29 <@Lily> Global: True; #dev: True
23:29 <@synnero> Lily--
23:29 <@Lily> Lily's karma is now -1
23:29 <@synnero> test++
23:33 <@synnero> `config plugins.karma.onlynicks 0
23:33 <@Lily> Done.
23:33 <@synnero> Lily++
23:33 <@Lily> Lily's karma is now 0
23:33 <@synnero> test--
23:33 <@Lily> test's karma is now 0
```

**Comment by ProgVal** [comment]
```
msg = ircmsgs.join(self.channel, prefix='hello!foo@bar')
self.irc.feedMsg(msg)
```

**Comment by GLolol** [comment]
Updated and rebased. Silly me!

**Pull request merged**
