### PR TITLE
QuoteGrabs: Add say command

### LINKED ISSUE #1030: QuoteGrabs: Add say command
The say command returns just the quote itself from a specific quote.

I have a diff that I made from what was used in the supybot instance in `#archlinux`, though it changes SqliteQuoteGrabsDB.get and QuoteGrabsRecord.\__str__ so that the get function lets you just return the quote text and so that printing a QuoteGrabsRecord with only the quote text set will just print the quote without the "said by" part.

Mostly I'm interested in 1) if this command is wanted upstream, and 2) whether someone can come up with another way of doing it than [this](http://sprunge.us/BZfQ?diff) that would be more likely to be accepted. If that's acceptable though I can open a PR.

### PR DESCRIPTION
**Pull request by kyrias**
The say command just returns the text of the grab, so you can get just
the quote from a specific qid.

Fixes #1030

### CODE REVIEW

**Comment by Mikaela** [comment]
Pull requests should be opened to the testing branch.

**Comment by ProgVal** [comment]
What is `self.at`?

**Comment by ProgVal** [comment]
nevermind

**Comment by kyrias** [comment]
@Mikaela Ah, sorry.

@ProgVal Any other questions? (This is the exact same patch as in #1030 btw)

**Comment by GermainZ** [comment]
Maybe that should be mentioned in the [contributions wiki page](http://doc.supybot.aperio.fr/en/latest/contribute/develop.html).

**Comment by kyrias** [comment]
Well, it's mentioned in CONTRIBUTING.md, I just fudged the hub command.

**Comment by Mikaela** [comment]
> Maybe that should be mentioned in the contributions wiki page as well.

Feel free to open pull request :) https://github.com/Limnoria/Limnoria-doc/blob/master/contribute/develop.rst

**Comment by ProgVal** [comment]
I updated the doc.

**Comment by ProgVal** [comment]
Merged manually.

**Pull request closed without merging**
