### PR TITLE
Factoids Plugin @whatis command --silentError Flag

### PR DESCRIPTION
**Pull request by t3chguy**
Allows for the @whatis command to silently fail if the flag is provided - not useful on its own but useful as part of nested commands.
Also automatically removed whitespace in empty lines - https://www.python.org/dev/peps/pep-0008/

### CODE REVIEW

**Comment by ProgVal** [comment]
I would prefer a command to do that.

**Comment by t3chguy** [comment]
A command like utilities ignore for Errors?

**Comment by GLolol** [comment]
The pull request looks like it only changes the `messages.pot`. Is that right? https://github.com/ProgVal/Limnoria/pull/1114/files?w=1

**Comment by t3chguy** [comment]
Hmm, something has gone wrong on my end - give me a second to remedy this @GLolol

**Comment by t3chguy** [comment]
Hmm @GLolol do you have any idea why its only using one of the changed files out of the referenced commit?

**Comment by t3chguy** [comment]
Weird - now its showing up as 2 files, and no actions listed as taken since the start

**Comment by GLolol** [comment]
Are you sure you committed properly? Looking at the `plugin.py` from your branch doesn't show any `silentError` things.

**Comment by t3chguy** [comment]
@GLolol the file is showing up in this PR now - did you have a look at my testing branch?
I can see (2) Files Changed at the top

**Comment by GLolol** [comment]
I don't see it. Did you forget to push?

**Comment by t3chguy** [comment]
Link to Referenced Commit: https://github.com/t3chguy/Limnoria/commit/5604ac30e5af44cf43fce7f5f37c7cc9a2e398be

**Comment by GLolol** [comment]
Nothing changes in `plugin.py` matching `silentError`...

**Comment by t3chguy** [comment]
That is the result of my GitHub client screwing up - one second

**Comment by ProgVal** [comment]
> A command like utilities ignore for Errors? 

yes

**Comment by ProgVal** [comment]
Or something in Conditional

**Pull request closed without merging**
