### PR TITLE
Dict: add an option to send 'dict' output to private

### LINKED ISSUE #841: Dict: add option to send messages in private
Dict can easily distrupt discussion on channl with high amount of mores. There should also be flag to override this by either sending it to query or channl.

### PR DESCRIPTION
**Pull request by GLolol**
Closes #841.

### CODE REVIEW

**Comment by GLolol** [comment]
The test fail is unrelated: [supybot-test segfaulted??!?](https://travis-ci.org/ProgVal/Limnoria/jobs/51675315#L3926)

**Comment by ProgVal** [comment]
“in order to reduce flooding” -> how does this plugin flood more than any other?

**Comment by Mikaela** [comment]
For example:

```
2015-02-22 12:00:22+0200 < Mikaela> @dict hello
2015-02-22 12:00:24+0200 <@Limnoria> gcide, wn, foldoc, and moby-thesaurus responded: wn: hello n 1: an expression of greeting; "every morning they exchanged polite hellos" [syn: {hello}, {hullo}, {hi}, {howdy}, {how- do-you-do}]; moby-thesaurus: 19 Moby Thesaurus words for "hello": accost, address, bob, bow, curtsy, embrace, greeting, hail, hand-clasp, handshake, how-do-you-do, hug, kiss, nod, salutation, salute, (3 more messages)
2015-02-22 12:00:27+0200 < Mikaela> @more
2015-02-22 12:00:28+0200 <@Limnoria> smile, smile of recognition, wave ; gcide: Hello \Hel*lo"\, interj. & n. An exclamation used as a greeting, to call attention, as an exclamation of surprise, or to encourage one. This variant of {Halloo} and {Holloo} has become the dominant form. In the United States, it is the most common greeting used in answering a telephone. [1913 Webster +PJC]; foldoc: hello, world hello <programming> (2 more messages)
2015-02-22 12:00:30+0200 < Mikaela> @more
2015-02-22 12:00:31+0200 <@Limnoria> The canonical, minimal, first program that a programmer writes in a new {programming language} or {development environment}. The program just prints "hello, world" to {standard output} in order to verify that the programmer can successfully edit, compile and run a simple program before embarking on anything more challenging. Hello, world is the first example program in the {C} programming book, (1 more message)
2015-02-22 12:00:33+0200 < Mikaela> @more
2015-02-22 12:00:33+0200 <@Limnoria> {K&R}, and the tradition has spread from there to pretty much every other language and many of their textbooks. Environments that generate an unreasonably large executable for this trivial test or which require a {hairy} compiler-linker invocation to generate it are considered bad. {Hello, World in over 400 programming languages (http://www.roesler-ac.de/wolfram/hello.htm)}. (2013-10-27)
```

Take another common word and you willl get even more lines, I think some words had more than that 50 lines of mores.

**Comment by Mikaela** [comment]
crane is another nice word.

**Comment by ProgVal** [comment]
That's not flooding…

**Comment by Mikaela** [comment]
what if I `@dict crane` and `@more` 18 times?

**Comment by ProgVal** [comment]
You could do `@echo foo` 19 times as well.

**Comment by GLolol** [comment]
`@more` doesn't go into private at all, you'd need to use an alias for that (load Reply, `aka add more "private more $*"`.

**Comment by Mikaela** [comment]
I would like this option with my bot.

**Comment by GLolol** [comment]
`git pull https://github.com/GLolol/Limnoria dict/inprivate` on your fork?

**Comment by Mikaela** [comment]
I don't want to diverce it from upstream Limnoria.

**Comment by GLolol** [comment]
You can do branchwork and create a new branch, leaving testing intact...

(Whatever, getting offtopic here)

**Comment by ProgVal** [comment]
What about `aka add dict "private dict"`?

**Comment by Mikaela** [comment]
That would require `defaultplugin dict aka` and still allow people to use `dict dict crane`.

**Comment by ProgVal** [comment]
People will always find a way to flood…

**Comment by Mikaela** [comment]
And those can be thought separately.

**Comment by ProgVal** [comment]
There is `supybot.abuse.flood` for that…

**Pull request closed without merging**
