### PR TITLE
strip duplicate nicks from @tell

### PR DESCRIPTION
**Pull request by cottongin**
Removes duplicate nicks from @tell <same nick>,<same nick>,<same nick> to avoid spam

### CODE REVIEW

**Comment by ProgVal** [comment]
It won't prevent users from using `@tell foo,foo*,foo**`

**Comment by cottongin** [comment]
No real way to fix that I can think of, without breaking wildcards completely.

**Comment by cottongin** [comment]
Upon testing foo*, foo**, foo*** on my end, it appears to work as intended

**Comment by ProgVal** [comment]
uh, actually, wildcards are not allowed, wtf

**Comment by ProgVal** [comment]
Nevermind, it's because the only `*` allowed is the last character.

**Comment by cottongin** [comment]
On further testing, since sets are unordered, it can actually break with `**` and `***`.  `*` works as intended.

**Pull request closed without merging**
